import { create } from "zustand";
export type Employee = {
  firstname: string;
  lastname: string;
  dob: string;
  startdate: string;
  department: string;
  street: string;
  city: string;
  state: string;
  "zip-code": number;
};

type EmployeeState = {
  employees: Employee[];
  addEmployee: (employee: Employee) => void;
};

export const useEmployeeState = create<EmployeeState>((set) => ({
  employees: [
    /* {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    },
    {
      firstname: "benoit test",
      lastname: "desnos",
      dob: "02/06/1990",
      startdate: "02/06/1990",
      department: "Human Resources",
      street: "street",
      city: "city",
      state: "CA",
      "zip-code": 1,
    },
    {
      firstname: "John",
      lastname: "Doe",
      dob: "01/01/1990",
      startdate: "01/01/2022",
      department: "Sales",
      street: "123 Main St",
      city: "New York",
      state: "NY",
      "zip-code": 10001,
    },
    {
      firstname: "Jane",
      lastname: "Smith",
      dob: "02/02/1995",
      startdate: "02/02/2022",
      department: "Marketing",
      street: "456 Elm St",
      city: "Los Angeles",
      state: "CA",
      "zip-code": 90001,
    },
    {
      firstname: "Michael",
      lastname: "Johnson",
      dob: "03/03/1985",
      startdate: "03/03/2022",
      department: "Finance",
      street: "789 Oak St",
      city: "Chicago",
      state: "IL",
      "zip-code": 60601,
    },
    {
      firstname: "Emily",
      lastname: "Brown",
      dob: "04/04/1992",
      startdate: "04/04/2022",
      department: "Engineering",
      street: "321 Pine St",
      city: "San Francisco",
      state: "CA",
      "zip-code": 94101,
    },
    {
      firstname: "David",
      lastname: "Wilson",
      dob: "05/05/1988",
      startdate: "05/05/2022",
      department: "Operations",
      street: "654 Cedar St",
      city: "Seattle",
      state: "WA",
      "zip-code": 98101,
    },
    {
      firstname: "Olivia",
      lastname: "Taylor",
      dob: "06/06/1993",
      startdate: "06/06/2022",
      department: "IT",
      street: "987 Maple St",
      city: "Austin",
      state: "TX",
      "zip-code": 78701,
    },
    {
      firstname: "James",
      lastname: "Anderson",
      dob: "07/07/1983",
      startdate: "07/07/2022",
      department: "Customer Service",
      street: "789 Walnut St",
      city: "Boston",
      state: "MA",
      "zip-code": 2108,
    },
    {
      firstname: "Sophia",
      lastname: "Martinez",
      dob: "08/08/1998",
      startdate: "08/08/2022",
      department: "Research",
      street: "654 Birch St",
      city: "Denver",
      state: "CO",
      "zip-code": 80202,
    },
    {
      firstname: "Daniel",
      lastname: "Garcia",
      dob: "09/09/1980",
      startdate: "09/09/2022",
      department: "Management",
      street: "321 Oak St",
      city: "Houston",
      state: "TX",
      "zip-code": 77002,
    },
    {
      firstname: "Isabella",
      lastname: "Lopez",
      dob: "10/10/1995",
      startdate: "10/10/2022",
      department: "Design",
      street: "987 Elm St",
      city: "Miami",
      state: "FL",
      "zip-code": 33101,
    }, */
  ],

  addEmployee: (employee) =>
    set((state) => ({ employees: [...state.employees, employee] })),
}));
